"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.StockDTO = exports.ShopCategoryDTO = exports.TicketDTO = exports.TicketMessageDTO = exports.HotelRequisitionDTO = exports.HotelDTO = exports.NewsDTO = exports.ServiceDTO = exports.CafeDTO = exports.EventDTO = exports.RestaurantDTO = exports.NotificationsDTO = exports.CreateProposalDTO = exports.CCreateCarouselDTO = exports.AdminDTO = exports.CLoginAdminDTO = exports.CUpdateUserDTO = exports.CJWTPayloadDTO = exports.CSendSMSDTO = exports.CSendCodeDTO = void 0;
// Classes
var auth_1 = require("./auth");
Object.defineProperty(exports, "CSendCodeDTO", { enumerable: true, get: function () { return auth_1.CSendCodeDTO; } });
Object.defineProperty(exports, "CSendSMSDTO", { enumerable: true, get: function () { return auth_1.CSendSMSDTO; } });
Object.defineProperty(exports, "CJWTPayloadDTO", { enumerable: true, get: function () { return auth_1.CJWTPayloadDTO; } });
var user_1 = require("./user");
Object.defineProperty(exports, "CUpdateUserDTO", { enumerable: true, get: function () { return user_1.CUpdateUserDTO; } });
var admin_1 = require("./admin");
Object.defineProperty(exports, "CLoginAdminDTO", { enumerable: true, get: function () { return admin_1.CLoginAdminDTO; } });
Object.defineProperty(exports, "AdminDTO", { enumerable: true, get: function () { return admin_1.AdminDTO; } });
var content_1 = require("./content");
Object.defineProperty(exports, "CCreateCarouselDTO", { enumerable: true, get: function () { return content_1.CCreateCarouselDTO; } });
Object.defineProperty(exports, "CreateProposalDTO", { enumerable: true, get: function () { return content_1.CreateProposalDTO; } });
var notifications_1 = require("./notifications");
Object.defineProperty(exports, "NotificationsDTO", { enumerable: true, get: function () { return notifications_1.NotificationsDTO; } });
var restaurant_1 = require("./restaurant");
Object.defineProperty(exports, "RestaurantDTO", { enumerable: true, get: function () { return restaurant_1.RestaurantDTO; } });
var event_1 = require("./event");
Object.defineProperty(exports, "EventDTO", { enumerable: true, get: function () { return event_1.EventDTO; } });
var cafe_1 = require("./cafe");
Object.defineProperty(exports, "CafeDTO", { enumerable: true, get: function () { return cafe_1.CafeDTO; } });
var service_1 = require("./service");
Object.defineProperty(exports, "ServiceDTO", { enumerable: true, get: function () { return service_1.ServiceDTO; } });
var news_1 = require("./news");
Object.defineProperty(exports, "NewsDTO", { enumerable: true, get: function () { return news_1.NewsDTO; } });
var hotel_1 = require("./hotel");
Object.defineProperty(exports, "HotelDTO", { enumerable: true, get: function () { return hotel_1.HotelDTO; } });
var hotel_requisition_1 = require("./hotel-requisition");
Object.defineProperty(exports, "HotelRequisitionDTO", { enumerable: true, get: function () { return hotel_requisition_1.HotelRequisitionDTO; } });
var ticket_1 = require("./ticket");
Object.defineProperty(exports, "TicketMessageDTO", { enumerable: true, get: function () { return ticket_1.TicketMessageDTO; } });
Object.defineProperty(exports, "TicketDTO", { enumerable: true, get: function () { return ticket_1.TicketDTO; } });
var shops_category_1 = require("./shops-category");
Object.defineProperty(exports, "ShopCategoryDTO", { enumerable: true, get: function () { return shops_category_1.ShopCategoryDTO; } });
var stock_1 = require("./stock");
Object.defineProperty(exports, "StockDTO", { enumerable: true, get: function () { return stock_1.StockDTO; } });
